# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: rytara/docker-node-zip

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn
          - cd build
          - zip -r ../zipfile.zip .
          - cd ..
          - curl -X POST -u $AzureCredUser:$AzureCredPass --data-binary @"zipfile.zip" https://buyer-ui-testing.scm.azurewebsites.net/api/zipdeploy
          - curl -X POST -u $AzureCredUser:$AzureCredPass --data-binary @"zipfile.zip" https://buyer-ui-staging.scm.azurewebsites.net/api/zipdeploy
          - curl -X POST -u $AzureCredUser:$AzureCredPass --data-binary @"zipfile.zip" https://buyer-ui-deploy.scm.azurewebsites.net/api/zipdeploy

