describe('Chat page', () => {
  it('Visits the chat page', () => {
    cy.visit('/')
    cy.url().should('include', '/home')
    cy.login()
    cy.get('a[href="/chat"]').click()
    cy.url().should('include', '/chat')
  })

  it('Chat with seller from chat page', () => {
    cy.get('a[href="/chat"]').click()
    cy.wait(5000)
    cy.get('[class^="thread-item"]').eq(0).click()
    const dateNow = 'Test chat on '+new Date().toString()
    cy.get('textarea').type(dateNow)
    cy.get('textarea').siblings('button').click()
    cy.wait(5000)
    cy.get('[class^="conversation--bubble"]').last().should('contain', dateNow)
  })

  it('Chat with seller from homepage', () => {
    cy.visit('/')
    cy.url().should('contain', '/home')
    cy.login()
    cy.get('div[data-testid="product-card"]').eq(0).find('div[data-testid="product-card-action"] > div').as('productCardAction1')
    cy.get('@productCardAction1').eq(0).find('a[data-testid="chat"]').click()
    cy.url().should('contain', '/chat/new')
    cy.wait(5000)
    const dateNow = 'Test chat on '+new Date().toString()
    cy.get('textarea').type(dateNow)
    cy.get('textarea').siblings('button').click()
    cy.wait(5000)
    cy.get('[class^="conversation--bubble"]').last().should('contain', dateNow)
  }) 
})
